browser:
  port: 9222
  verify: true


# 用户配置（务必保持账号密码与 iSmart 中已登录的相同）
user:
  username: <用户名>  # 用户名/手机号
  password: <密码>  # 密码

# 答题配置
paper:
  skip-finished: true  # 跳过已完成任务

  # 不同题目类型的随机得分
  random-score:
    - 1  # 1.单选
    - 1  # 2.多选
    - 1  # 3.判断
    - [ 0.9, 1 ]  # 4.填空
    -
    - [ 0.9, 1 ]  # 6.连线
    -
    - 1  # 8.匹配
    - [ 0.7, 1 ]  # 9.口语跟读
    - [ 0.7, 1 ]  # 10.短文改错
    - 1  # 11.选词填空
    -
  defaults: pause  # 未知题型的处理方式（暂停或使用默认得分）
#  defaults: [ 1, 1 ]

  random-time: [ 60, 120 ]  # 每道题的随机用时（秒）
